<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <link name = "laser_frame">
        <visual>
            <geometry>
                <cylinder radius = "${wheel_radius /2}" length = "${wheel_length}"/>
            </geometry>
            <origin xyz = "0 0 ${wheel_length / 2}" rpy = "0 0 0" />
            <material name = "red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius = "${wheel_radius / 2}" length = "${wheel_length}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
        </collision>
        <xacro:cylinder_inertia m = "1.0" r = "${wheel_radius / 2}" l = "${wheel_length}"
            o_xyz = "0 0 0" o_rpy = "0 0 0" />
    </link>

    <joint name = "laser_joint" type = "fixed">
        <parent link = "base_link" />
        <child link = "laser_frame" />
        <origin xyz = "${base_length / 3} 0 ${base_height}" rpy = "0 0 0"/>
    </joint>
</robot>
